// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// statint
List statint(NumericMatrix K, NumericVector Rtemp, double R0, double r1, double r2);
RcppExport SEXP _kerSeg_statint(SEXP KSEXP, SEXP RtempSEXP, SEXP R0SEXP, SEXP r1SEXP, SEXP r2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type K(KSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Rtemp(RtempSEXP);
    Rcpp::traits::input_parameter< double >::type R0(R0SEXP);
    Rcpp::traits::input_parameter< double >::type r1(r1SEXP);
    Rcpp::traits::input_parameter< double >::type r2(r2SEXP);
    rcpp_result_gen = Rcpp::wrap(statint(K, Rtemp, R0, r1, r2));
    return rcpp_result_gen;
END_RCPP
}
// skew
NumericVector skew(NumericMatrix K, NumericVector Rtemp, NumericVector Rtemp2, double R0, double R2);
RcppExport SEXP _kerSeg_skew(SEXP KSEXP, SEXP RtempSEXP, SEXP Rtemp2SEXP, SEXP R0SEXP, SEXP R2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type K(KSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Rtemp(RtempSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Rtemp2(Rtemp2SEXP);
    Rcpp::traits::input_parameter< double >::type R0(R0SEXP);
    Rcpp::traits::input_parameter< double >::type R2(R2SEXP);
    rcpp_result_gen = Rcpp::wrap(skew(K, Rtemp, Rtemp2, R0, R2));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_kerSeg_statint", (DL_FUNC) &_kerSeg_statint, 5},
    {"_kerSeg_skew", (DL_FUNC) &_kerSeg_skew, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_kerSeg(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
