# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

statint <- function(K, Rtemp, R0, r1, r2) {
    .Call(`_kerSeg_statint`, K, Rtemp, R0, r1, r2)
}

skew <- function(K, Rtemp, Rtemp2, R0, R2) {
    .Call(`_kerSeg_skew`, K, Rtemp, Rtemp2, R0, R2)
}

